name: C2SIM Problem Report / Change Request
description: Please use this template to create a new C2SIM issue.
title: "[C2SIM Issue]: "
labels: ["issue", "triage"]
assignees:
  - octocat
body:
   - type: input
    id: submitterName
    attributes:
      label: Submitter Name
      description: Submitter Name(s)
      placeholder: Submitter Name(s)
    validations:
      required: true
