name: C2SIM Problem Report / Change Request
description: Please use this template to create a new C2SIM issue.
title: "[C2SIM Issue]: "
labels: ["issue", "triage"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this C2SIM Issue!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: input
    id: submitterName
    attributes:
      label: Submitter Name
      description: Submitter Name(s)
      placeholder: Submitter Name(s)
    validations:
      required: true
